In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

import sklearn
from sklearn.datasets import load_digits

In [4]:
data = load_digits()

In [7]:
X, y = data.data, data.target

In [9]:
X, X.shape

(array([[ 0.,  0.,  5., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ..., 10.,  0.,  0.],
        [ 0.,  0.,  0., ..., 16.,  9.,  0.],
        ...,
        [ 0.,  0.,  1., ...,  6.,  0.,  0.],
        [ 0.,  0.,  2., ..., 12.,  0.,  0.],
        [ 0.,  0., 10., ..., 12.,  1.,  0.]]),
 (1797, 64))

In [10]:
y, y.shape

(array([0, 1, 2, ..., 8, 9, 8]), (1797,))

In [12]:
from sklearn.tree import DecisionTreeClassifier

In [15]:
from sklearn.model_selection import cross_val_score

clf = DecisionTreeClassifier()
cv_scores = cross_val_score(clf, X, y, n_jobs=-1, cv=10)
cv_scores

array([0.81666667, 0.85555556, 0.81666667, 0.79444444, 0.76666667,
       0.89444444, 0.87777778, 0.81564246, 0.79329609, 0.81005587])

In [16]:
cv_scores.mean()

0.8241216635630042

In [17]:
from sklearn.ensemble import BaggingClassifier

In [18]:
def model_cv_score(estimator):
    return cross_val_score(estimator, X, y, n_jobs=-1, cv=10).mean()

In [19]:
bg = BaggingClassifier(n_estimators=100)

In [20]:
model_cv_score(bg)

0.9259404096834267

In [21]:
bg_sqrt = BaggingClassifier(max_features=8, n_estimators=100)

In [22]:
model_cv_score(bg_sqrt)

0.9287585350713842

In [26]:
dcs = DecisionTreeClassifier(max_features=8, random_state=8)

bg_ = BaggingClassifier(n_estimators=100, base_estimator=dcs)

cross_val_score(bg_, X, y, cv=10, n_jobs=-1).mean()

0.9504686530105524

In [30]:
from sklearn.ensemble import RandomForestClassifier

rf_ = RandomForestClassifier()
model_cv_score(rf_)

0.9465735567970205