In [8]:
from sklearn import datasets
from sklearn import model_selection

import numpy as np

In [9]:
iris = datasets.load_iris()

In [41]:
print(iris.data)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [10]:
train_data, test_data, train_labels, test_labels = model_selection.train_test_split(iris.data, iris.target, test_size=0.3)

In [11]:
print(train_data)
print(test_data)

[[4.8 3.  1.4 0.3]
 [4.4 2.9 1.4 0.2]
 [6.9 3.1 5.4 2.1]
 [6.8 2.8 4.8 1.4]
 [5.8 2.7 3.9 1.2]
 [6.3 2.5 4.9 1.5]
 [4.9 3.6 1.4 0.1]
 [6.  3.  4.8 1.8]
 [5.  3.4 1.5 0.2]
 [7.  3.2 4.7 1.4]
 [6.  2.9 4.5 1.5]
 [4.5 2.3 1.3 0.3]
 [5.2 4.1 1.5 0.1]
 [6.1 2.6 5.6 1.4]
 [6.3 3.4 5.6 2.4]
 [5.9 3.  5.1 1.8]
 [5.1 3.3 1.7 0.5]
 [7.1 3.  5.9 2.1]
 [5.5 2.6 4.4 1.2]
 [5.7 3.  4.2 1.2]
 [6.6 2.9 4.6 1.3]
 [6.9 3.2 5.7 2.3]
 [5.1 3.5 1.4 0.2]
 [7.4 2.8 6.1 1.9]
 [5.4 3.  4.5 1.5]
 [6.7 3.3 5.7 2.5]
 [5.1 2.5 3.  1.1]
 [7.7 3.8 6.7 2.2]
 [4.7 3.2 1.6 0.2]
 [6.7 3.1 5.6 2.4]
 [5.7 2.5 5.  2. ]
 [6.4 3.1 5.5 1.8]
 [6.4 2.9 4.3 1.3]
 [6.7 3.  5.  1.7]
 [5.  3.6 1.4 0.2]
 [6.6 3.  4.4 1.4]
 [5.  3.5 1.3 0.3]
 [5.6 2.9 3.6 1.3]
 [4.4 3.  1.3 0.2]
 [5.4 3.9 1.3 0.4]
 [5.1 3.8 1.5 0.3]
 [6.  3.4 4.5 1.6]
 [5.5 2.5 4.  1.3]
 [6.9 3.1 4.9 1.5]
 [5.4 3.4 1.5 0.4]
 [4.8 3.4 1.6 0.2]
 [5.2 3.5 1.5 0.2]
 [5.  3.4 1.6 0.4]
 [6.5 3.  5.5 1.8]
 [6.5 3.2 5.1 2. ]
 [5.2 2.7 3.9 1.4]
 [5.7 2.8 4.1 1.3]
 [6.  2.2 4.

In [14]:
print(train_labels)
print(test_labels)

[0 0 2 1 1 1 0 2 0 1 1 0 0 2 2 2 0 2 1 1 1 2 0 2 1 2 1 2 0 2 2 2 1 1 0 1 0
 1 0 0 0 1 1 1 0 0 0 0 2 2 1 1 1 0 1 2 0 2 1 1 0 1 2 2 1 1 1 0 1 1 0 0 1 1
 0 2 0 2 0 2 2 0 2 0 2 0 0 1 2 1 1 0 2 0 2 2 1 0 2 1 0 1 0 2 2]
[2 2 2 2 1 2 2 1 0 1 2 1 2 2 0 0 1 0 0 0 1 2 2 1 2 1 2 0 0 0 0 2 2 1 0 2 2
 1 1 1 0 2 1 0 0]


In [25]:
print(f"{len(train_labels)}, {len(test_labels)}")

105, 45


In [51]:
kf = model_selection.KFold(n_splits=4, shuffle=True)

In [53]:
for i, (train_index, test_index) in enumerate(kf.split(iris)):
    print(f"{i}:, {train_index}, {test_index}")

0:, [0 1 2 3 5 7], [4 6]
1:, [0 2 3 4 5 6], [1 7]
2:, [0 1 4 5 6 7], [2 3]
3:, [1 2 3 4 6 7], [0 5]


In [ ]:
skf = model_selection.StratifiedKFold(n)